In [1]:
# # if ee was updated, authenticate first
# import ee

# ee.Authenticate()
# ee.Initialize()

In [1]:
from scigee_test import *

In [3]:
# dir(gf)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'draw_image_obs',
 'ee',
 'filter_collection',
 'get_cfsv2',
 'get_cloud',
 'get_collection_size',
 'get_date',
 'get_image',
 'get_image_bandnames',
 'get_proj',
 'get_scale',
 'get_toms_omi_ozone',
 'landsat7_evi',
 'landsat7_srt1',
 'modis_aod',
 'modis_gpp',
 'modis_lai_fpar',
 'modis_net_evapo',
 'modis_reflectance',
 'np',
 'pd',
 'pml_v2_water',
 'proj_epsg',
 'region2array',
 'region2arrayB',
 'region2array_obs',
 's5p_hcho',
 's5p_no2',
 's5p_o3',
 'timeseries2df']

In [2]:
import ee

# YRD
minlon = 114.4
maxlon = 122.7
minlat = 27.1
maxlat = 35.3
 
roi = ee.Geometry.Polygon(
    [[
      [minlon, maxlat],
      [maxlon, maxlat],
      [maxlon, minlat],
      [minlon, minlat]
    ]]
)
 
date_range = ["2020-01-01", "2020-01-10"]
name = "YRD" # MANUALLY INPUT HERE

collection, bands, label_bands, scale = DataInfo.s5p_o3()
collection_o3 = gf.filter_collection(collection, date_range, roi)

idx = 5
image1 = gf.get_image(collection_o3, idx)
# print(type(image1))
image1 = image1.select('O3_column_number_density')

print(gf.get_image_bandnames(image1))

df_region = gf.region2array(image1, roi, 10000, max_pixels = 1e13, mask_value = -9999)

['O3_column_number_density']

In [3]:
df_region

      O3_column_number_density   latitude   longitude
0                     0.106507  27.145139  114.429165
1                     0.106591  27.145139  114.518996
2                     0.106599  27.145139  114.608828
3                     0.107132  27.145139  114.698659
4                     0.105853  27.145139  114.788491
...                        ...        ...         ...
8501                  0.133557  35.319808  121.166529
8502                  0.133842  35.319808  121.256361
8503                  0.133548  35.319808  121.346192
8504                  0.134465  35.319808  121.436024
8505                  0.133754  35.319808  121.525855

[8506 rows x 3 columns]

In [4]:
df_ts = gf.timeseries2df(collection_o3, bands, label_bands, (minlon + maxlon)/2, (minlat + maxlat)/2, date_range, scale)

In [5]:
df_ts

,o3_vcd,o3_amf,o3_scd,o3_temperature,s5p_cloud_fraction,s5p_sen_azi,s5p_sen_zen,s5p_sun_zai,s5p_sun_zen
2020-01-01 05:21:02,0.113382,2.789402,0.320813,232.732610,0.456757,-101.780194,12.838212,-160.036225,56.936740
2020-01-02 05:01:03,0.112254,2.894220,0.330216,232.063592,1.000000,73.393652,20.509663,-165.125673,55.663288
2020-01-03 04:41:03,0.113053,3.210740,0.369231,229.941349,1.000000,68.675941,45.644697,-170.388325,54.699463
2020-01-04 04:21:02,0.114392,3.694773,0.431498,225.789946,1.000000,64.705701,60.739648,-175.644329,54.141266
2020-01-04 06:01:03,0.115629,4.074961,0.473728,225.608643,0.953831,-91.615295,62.890079,-149.318787,60.649437
2020-01-05 05:46:03,0.113669,3.291410,0.380402,229.979377,0.672643,-95.495678,47.810865,-153.955887,58.551502
2020-01-06 05:26:02,0.112862,2.959936,0.338841,228.770218,1.000000,-100.108864,23.451162,-158.812180,56.782513
2020-01-07 05:06:02,0.126169,2.899259,0.371041,233.537491,1.000000,75.045174,9.969246,-163.924561,55.369293
2020-01-08 04:46:03,0.121068,3.042106,0.375595,228.966222,0.830296,70.191245,38.480564,-169.148958,54.307620
2020-01-09 04:31:02,0.122749,3.451291,0.432791,230.811893,1.000000,65.918815,56.699759,-174.538683,53.537684

In [9]:
dir(ee)

['Algorithms',
 'ApiFunction',
 'Array',
 'Authenticate',
 'Blob',
 'Classifier',
 'Clusterer',
 'Collection',
 'ComputedObject',
 'ConfusionMatrix',
 'CustomFunction',
 'Date',
 'DateRange',
 'Dictionary',
 'EEException',
 'Element',
 'Encodable',
 'ErrorMargin',
 'Feature',
 'FeatureCollection',
 'Filter',
 'Function',
 'Geometry',
 'Image',
 'ImageCollection',
 'Initialize',
 'Join',
 'Kernel',
 'List',
 'Model',
 'Number',
 'PixelType',
 'Projection',
 'Reducer',
 'Reset',
 'SelectorSet',
 'Serializer',
 'ServiceAccountCredentials',
 'String',
 'Terrain',
 '_AlgorithmsContainer',
 '_HAS_DYNAMIC_ATTRIBUTES',
 '_InitializeGeneratedClasses',
 '_InitializeUnboundMethods',
 '_MakeClass',
 '_Promote',
 '_ResetGeneratedClasses',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_cloud_api_utils',
 '_generatedClasses',
 '_helpers',
 'apifunction',
 'apply',
 'batch',
 'call',
 'collection',
 'collections',
 'computedobject',
 'customfunction',
 'data',
 'datetime',
 'deprecation',
 'deserializer',
 'dictionary',
 'ee_date',
 'ee_exception',
 'ee_list',
 'ee_number',
 'ee_string',
 'ee_types',
 'element',
 'encodable',
 'feature',
 'featurecollection',
 'filter',
 'function',
 'geometry',
 'image',
 'imagecollection',
 'inspect',
 'numbers',
 'oauth',
 'os',
 'profilePrinting',
 'serializer',
 'six',
 'terrain',
 'types']